import { Router } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import analysesRouter from "./analyses.js";
import statsRouter from "./stats.js";
import recommendationsRouter from "./recommendations.js";
const router = Router();
router.use(healthRouter);
router.use(authRouter);
router.use(analysesRouter);
router.use(statsRouter);
router.use(recommendationsRouter);
export default router;
